### PR TITLE
Fix SMF handling for some MIDIs

### LINKED ISSUE #182: Standard MIDI with only 1 track is treated as empty
Standard MIDI file (including SMF type 0) with only 1 track is treated as empty.
https://github.com/sdercolin/utaformatix3/blob/17de7cbe9fa0a0fca63e18f27b563a2f07bf85cc/core/src/main/kotlin/core/io/StandardMid.kt#L39

Idea: Parse all tracks first, and delete the first track if it's empty (to remove a track which is used only for including things like tempos)

### PR DESCRIPTION
**Pull request by sevenc-nanashi**
Fixes #182 .

### CODE REVIEW

File: core/src/main/kotlin/core/io/StandardMid.kt [hunk 1]
```diff
@@ -36,8 +36,14 @@ object StandardMid {
             warnings,
         )
 
-        val tracks = midiTracks.drop(1).mapIndexed { index, midiTrack ->
+        val tracks = midiTracks.mapIndexed { index, midiTrack ->
             parseTrack(index, timeDivision, tickPrefix, midiTrack, params.defaultLyric)
+        }.toMutableList()
```
Comment (sdercolin) [inline core/src/main/kotlin/core/io/StandardMid.kt:41]: I guess we can just filter all tracks to remove empty ones?
```kotlin
        val tracks = midiTracks.mapIndexed { index, midiTrack ->
            parseTrack(index, timeDivision, tickPrefix, midiTrack, params.defaultLyric)
        }.filter { it.notes.isNotEmpty() }
```

Comment (sevenc-nanashi) [reply core/src/main/kotlin/core/io/StandardMid.kt:41]: I tried to keep old behaviors as much as possible. Is it okay to remove all empty tracks?

Comment (sdercolin) [reply core/src/main/kotlin/core/io/StandardMid.kt:41]: Right, let's keep the original behavior 👍

**Review by sdercolin — APPROVED** [review]
